### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by thominj**
I needed a way to test redirects, and I found that adding a return statement to the CI Unit redirect helper gives us a way to check the input parameters, sort of like a test mock would.

### CODE REVIEW

**Comment by Celc** [comment]
How are you using that?

**Comment by thominj** [comment]
I'm having the system under test return the result of the redirect. Instead of:

```php
if ($something)
{
    redirect();
}
```

```php
if ($something)
{
    return redirect();
}
```

Not ideal, since you have to modify the test subject, but I couldn't think of another way to mock that function. Since CI_url_helper is already a test double, this is pretty close to the "right" way to do it.

**Comment by thominj** [comment]
Ignore that "close" please - I accidentally clicked the wrong button.

**Comment by thominj** [comment]
You know what - now I see that there is already an assertRedirects in the test case. I'll close this and just use that.

**Comment by Celc** [comment]
:+1: It should be possible to exit up the stack using an exception if we patched PHPUnit to ignore it if I ever get around to doing that.

It should also be possible to change `assertRedirect` to allow checking for `$status_code` as well as `$method` should you need that.

**Comment by thominj** [comment]
Cool - I like the idea of modifying assertRedirect if we can do it. I don't
need it now but if it comes up later I'll try to implement that.

**Pull request closed without merging**
